# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3ce112994d33a12fc5cee8722efecafefd949afe948c5913993d370f842a7c5407b43b2c15d98f8c0045a2fcf563f7b725d8d060c74856c93de1e4534c3483b

test:
  secret_key_base: c4e5bc41084df175ad8e098122bd96156e77c72c41ef5ed10717f283fec5f0403edb45dd5f6c237a89fba7fdc185cb45565961ddd45083d2a3b9651265705873

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
